////------------------------------------------------------------------------------
//// <auto-generated>
////     このコードはツールによって生成されました。
////     ランタイム バージョン:4.0.30319.42000
////
////     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
////     コードが再生成されるときに損失したりします。
//// </auto-generated>
////------------------------------------------------------------------------------

//using System.Xml.Serialization;

//// 
//// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
//// 


///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class scaling {
    
//    private string xField;
    
//    private string yField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string x {
//        get {
//            return this.xField;
//        }
//        set {
//            this.xField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string y {
//        get {
//            return this.yField;
//        }
//        set {
//            this.yField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class addData {
    
//    private addDataData[] dataField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("data")]
//    public addDataData[] data {
//        get {
//            return this.dataField;
//        }
//        set {
//            this.dataField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class addDataData {
    
//    private string projectInformationField;
    
//    private string elementTypeField;
    
//    private string callTypeField;
    
//    private string objectIdField;
    
//    private addDataDataProjectStructureObject[][] projectStructureField;
    
//    private string nameField;
    
//    private string handleUnknownField;
    
//    /// <remarks/>
//    public string ProjectInformation {
//        get {
//            return this.projectInformationField;
//        }
//        set {
//            this.projectInformationField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string ElementType {
//        get {
//            return this.elementTypeField;
//        }
//        set {
//            this.elementTypeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
//    public string CallType {
//        get {
//            return this.callTypeField;
//        }
//        set {
//            this.callTypeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string ObjectId {
//        get {
//            return this.objectIdField;
//        }
//        set {
//            this.objectIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("Object", typeof(addDataDataProjectStructureObject), IsNullable=false)]
//    public addDataDataProjectStructureObject[][] ProjectStructure {
//        get {
//            return this.projectStructureField;
//        }
//        set {
//            this.projectStructureField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string handleUnknown {
//        get {
//            return this.handleUnknownField;
//        }
//        set {
//            this.handleUnknownField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class addDataDataProjectStructureObject {
    
//    private string nameField;
    
//    private string objectIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string Name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string ObjectId {
//        get {
//            return this.objectIdField;
//        }
//        set {
//            this.objectIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class variable {
    
//    private variableType[] typeField;
    
//    private connectionPointInConnection[][] connectionPointInField;
    
//    private connectionPointOut[] connectionPointOutField;
    
//    private string nameField;
    
//    private string formalParameterField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("type")]
//    public variableType[] type {
//        get {
//            return this.typeField;
//        }
//        set {
//            this.typeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("connection", typeof(connectionPointInConnection), IsNullable=false)]
//    public connectionPointInConnection[][] connectionPointIn {
//        get {
//            return this.connectionPointInField;
//        }
//        set {
//            this.connectionPointInField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("connectionPointOut")]
//    public connectionPointOut[] connectionPointOut {
//        get {
//            return this.connectionPointOutField;
//        }
//        set {
//            this.connectionPointOutField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string formalParameter {
//        get {
//            return this.formalParameterField;
//        }
//        set {
//            this.formalParameterField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class variableType {
    
//    private string tIMEField;
    
//    private string bOOLField;
    
//    private variableTypeDerived[] derivedField;
    
//    /// <remarks/>
//    public string TIME {
//        get {
//            return this.tIMEField;
//        }
//        set {
//            this.tIMEField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string BOOL {
//        get {
//            return this.bOOLField;
//        }
//        set {
//            this.bOOLField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("derived")]
//    public variableTypeDerived[] derived {
//        get {
//            return this.derivedField;
//        }
//        set {
//            this.derivedField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class variableTypeDerived {
    
//    private string nameField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class connectionPointInConnection {
    
//    private string refLocalIdField;
    
//    private string formalParameterField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string refLocalId {
//        get {
//            return this.refLocalIdField;
//        }
//        set {
//            this.refLocalIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string formalParameter {
//        get {
//            return this.formalParameterField;
//        }
//        set {
//            this.formalParameterField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class connectionPointOut {
    
//    private string expressionField;
    
//    private string formalParameterField;
    
//    /// <remarks/>
//    public string expression {
//        get {
//            return this.expressionField;
//        }
//        set {
//            this.expressionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string formalParameter {
//        get {
//            return this.formalParameterField;
//        }
//        set {
//            this.formalParameterField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class connectionPointIn {
    
//    private connectionPointInConnection[] connectionField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("connection")]
//    public connectionPointInConnection[] connection {
//        get {
//            return this.connectionField;
//        }
//        set {
//            this.connectionField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class position {
    
//    private string xField;
    
//    private string yField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string x {
//        get {
//            return this.xField;
//        }
//        set {
//            this.xField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string y {
//        get {
//            return this.yField;
//        }
//        set {
//            this.yField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.plcopen.org/xml/tc6_0200", IsNullable=false)]
//public partial class project {
    
//    private object[] itemsField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("addData", typeof(addData))]
//    [System.Xml.Serialization.XmlElementAttribute("connectionPointIn", typeof(connectionPointIn))]
//    [System.Xml.Serialization.XmlElementAttribute("connectionPointOut", typeof(connectionPointOut))]
//    [System.Xml.Serialization.XmlElementAttribute("contentHeader", typeof(projectContentHeader))]
//    [System.Xml.Serialization.XmlElementAttribute("fileHeader", typeof(projectFileHeader))]
//    [System.Xml.Serialization.XmlElementAttribute("instances", typeof(projectInstances))]
//    [System.Xml.Serialization.XmlElementAttribute("position", typeof(position))]
//    [System.Xml.Serialization.XmlElementAttribute("scaling", typeof(scaling))]
//    [System.Xml.Serialization.XmlElementAttribute("types", typeof(projectTypes))]
//    [System.Xml.Serialization.XmlElementAttribute("variable", typeof(variable))]
//    public object[] Items {
//        get {
//            return this.itemsField;
//        }
//        set {
//            this.itemsField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectContentHeader {
    
//    private projectContentHeaderCoordinateInfo[] coordinateInfoField;
    
//    private addDataData[][] addDataField;
    
//    private string nameField;
    
//    private string modificationDateTimeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("coordinateInfo")]
//    public projectContentHeaderCoordinateInfo[] coordinateInfo {
//        get {
//            return this.coordinateInfoField;
//        }
//        set {
//            this.coordinateInfoField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("data", typeof(addDataData), IsNullable=false)]
//    public addDataData[][] addData {
//        get {
//            return this.addDataField;
//        }
//        set {
//            this.addDataField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string modificationDateTime {
//        get {
//            return this.modificationDateTimeField;
//        }
//        set {
//            this.modificationDateTimeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectContentHeaderCoordinateInfo {
    
//    private scaling[][] fbdField;
    
//    private scaling[][] ldField;
    
//    private scaling[][] sfcField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("scaling", typeof(scaling), IsNullable=false)]
//    public scaling[][] fbd {
//        get {
//            return this.fbdField;
//        }
//        set {
//            this.fbdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("scaling", typeof(scaling), IsNullable=false)]
//    public scaling[][] ld {
//        get {
//            return this.ldField;
//        }
//        set {
//            this.ldField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("scaling", typeof(scaling), IsNullable=false)]
//    public scaling[][] sfc {
//        get {
//            return this.sfcField;
//        }
//        set {
//            this.sfcField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectFileHeader {
    
//    private string companyNameField;
    
//    private string productNameField;
    
//    private string productVersionField;
    
//    private string creationDateTimeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string companyName {
//        get {
//            return this.companyNameField;
//        }
//        set {
//            this.companyNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string productName {
//        get {
//            return this.productNameField;
//        }
//        set {
//            this.productNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string productVersion {
//        get {
//            return this.productVersionField;
//        }
//        set {
//            this.productVersionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string creationDateTime {
//        get {
//            return this.creationDateTimeField;
//        }
//        set {
//            this.creationDateTimeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectInstances {
    
//    private string configurationsField;
    
//    /// <remarks/>
//    public string configurations {
//        get {
//            return this.configurationsField;
//        }
//        set {
//            this.configurationsField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypes {
    
//    private string dataTypesField;
    
//    private projectTypesPousPou[][] pousField;
    
//    /// <remarks/>
//    public string dataTypes {
//        get {
//            return this.dataTypesField;
//        }
//        set {
//            this.dataTypesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("pou", typeof(projectTypesPousPou), IsNullable=false)]
//    public projectTypesPousPou[][] pous {
//        get {
//            return this.pousField;
//        }
//        set {
//            this.pousField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPou {
    
//    private variable[][][] interfaceField;
    
//    private projectTypesPousPouBodyLD[][] bodyField;
    
//    private addDataData[][] addDataField;
    
//    private string nameField;
    
//    private string pouTypeField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("localVars", typeof(variable[]), IsNullable=false)]
//    [System.Xml.Serialization.XmlArrayItemAttribute("variable", typeof(variable), IsNullable=false, NestingLevel=1)]
//    public variable[][][] @interface {
//        get {
//            return this.interfaceField;
//        }
//        set {
//            this.interfaceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("LD", typeof(projectTypesPousPouBodyLD), IsNullable=false)]
//    public projectTypesPousPouBodyLD[][] body {
//        get {
//            return this.bodyField;
//        }
//        set {
//            this.bodyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("data", typeof(addDataData), IsNullable=false)]
//    public addDataData[][] addData {
//        get {
//            return this.addDataField;
//        }
//        set {
//            this.addDataField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string name {
//        get {
//            return this.nameField;
//        }
//        set {
//            this.nameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string pouType {
//        get {
//            return this.pouTypeField;
//        }
//        set {
//            this.pouTypeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLD {
    
//    private projectTypesPousPouBodyLDLeftPowerRail[] leftPowerRailField;
    
//    private projectTypesPousPouBodyLDComment[] commentField;
    
//    private projectTypesPousPouBodyLDVendorElement[] vendorElementField;
    
//    private projectTypesPousPouBodyLDContact[] contactField;
    
//    private projectTypesPousPouBodyLDInVariable[] inVariableField;
    
//    private projectTypesPousPouBodyLDBlock[] blockField;
    
//    private projectTypesPousPouBodyLDCoil[] coilField;
    
//    private projectTypesPousPouBodyLDRightPowerRail[] rightPowerRailField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("leftPowerRail")]
//    public projectTypesPousPouBodyLDLeftPowerRail[] leftPowerRail {
//        get {
//            return this.leftPowerRailField;
//        }
//        set {
//            this.leftPowerRailField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("comment")]
//    public projectTypesPousPouBodyLDComment[] comment {
//        get {
//            return this.commentField;
//        }
//        set {
//            this.commentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("vendorElement")]
//    public projectTypesPousPouBodyLDVendorElement[] vendorElement {
//        get {
//            return this.vendorElementField;
//        }
//        set {
//            this.vendorElementField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("contact")]
//    public projectTypesPousPouBodyLDContact[] contact {
//        get {
//            return this.contactField;
//        }
//        set {
//            this.contactField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("inVariable")]
//    public projectTypesPousPouBodyLDInVariable[] inVariable {
//        get {
//            return this.inVariableField;
//        }
//        set {
//            this.inVariableField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("block")]
//    public projectTypesPousPouBodyLDBlock[] block {
//        get {
//            return this.blockField;
//        }
//        set {
//            this.blockField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("coil")]
//    public projectTypesPousPouBodyLDCoil[] coil {
//        get {
//            return this.coilField;
//        }
//        set {
//            this.coilField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("rightPowerRail")]
//    public projectTypesPousPouBodyLDRightPowerRail[] rightPowerRail {
//        get {
//            return this.rightPowerRailField;
//        }
//        set {
//            this.rightPowerRailField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDLeftPowerRail {
    
//    private position[] positionField;
    
//    private connectionPointOut[] connectionPointOutField;
    
//    private string localIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("connectionPointOut")]
//    public connectionPointOut[] connectionPointOut {
//        get {
//            return this.connectionPointOutField;
//        }
//        set {
//            this.connectionPointOutField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDComment {
    
//    private position[] positionField;
    
//    private projectTypesPousPouBodyLDCommentContent[] contentField;
    
//    private string localIdField;
    
//    private string heightField;
    
//    private string widthField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("content")]
//    public projectTypesPousPouBodyLDCommentContent[] content {
//        get {
//            return this.contentField;
//        }
//        set {
//            this.contentField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string height {
//        get {
//            return this.heightField;
//        }
//        set {
//            this.heightField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string width {
//        get {
//            return this.widthField;
//        }
//        set {
//            this.widthField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDCommentContent {
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDVendorElement {
    
//    private position[] positionField;
    
//    private projectTypesPousPouBodyLDVendorElementAlternativeText[] alternativeTextField;
    
//    private addDataData[][] addDataField;
    
//    private string localIdField;
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("alternativeText")]
//    public projectTypesPousPouBodyLDVendorElementAlternativeText[] alternativeText {
//        get {
//            return this.alternativeTextField;
//        }
//        set {
//            this.alternativeTextField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("data", typeof(addDataData), IsNullable=false)]
//    public addDataData[][] addData {
//        get {
//            return this.addDataField;
//        }
//        set {
//            this.addDataField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDVendorElementAlternativeText {
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDContact {
    
//    private string connectionPointOutField;
    
//    private string variableField;
    
//    private position[] positionField;
    
//    private connectionPointInConnection[][] connectionPointInField;
    
//    private string localIdField;
    
//    private string negatedField;
    
//    private string storageField;
    
//    private string edgeField;
    
//    /// <remarks/>
//    public string connectionPointOut {
//        get {
//            return this.connectionPointOutField;
//        }
//        set {
//            this.connectionPointOutField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string variable {
//        get {
//            return this.variableField;
//        }
//        set {
//            this.variableField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("connection", typeof(connectionPointInConnection), IsNullable=false)]
//    public connectionPointInConnection[][] connectionPointIn {
//        get {
//            return this.connectionPointInField;
//        }
//        set {
//            this.connectionPointInField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string negated {
//        get {
//            return this.negatedField;
//        }
//        set {
//            this.negatedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string storage {
//        get {
//            return this.storageField;
//        }
//        set {
//            this.storageField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string edge {
//        get {
//            return this.edgeField;
//        }
//        set {
//            this.edgeField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDInVariable {
    
//    private string connectionPointOutField;
    
//    private string expressionField;
    
//    private position[] positionField;
    
//    private string localIdField;
    
//    /// <remarks/>
//    public string connectionPointOut {
//        get {
//            return this.connectionPointOutField;
//        }
//        set {
//            this.connectionPointOutField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string expression {
//        get {
//            return this.expressionField;
//        }
//        set {
//            this.expressionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDBlock {
    
//    private string inOutVariablesField;
    
//    private position[] positionField;
    
//    private variable[][] inputVariablesField;
    
//    private variable[][] outputVariablesField;
    
//    private addDataData[][] addDataField;
    
//    private string localIdField;
    
//    private string typeNameField;
    
//    private string instanceNameField;
    
//    /// <remarks/>
//    public string inOutVariables {
//        get {
//            return this.inOutVariablesField;
//        }
//        set {
//            this.inOutVariablesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("variable", typeof(variable), IsNullable=false)]
//    public variable[][] inputVariables {
//        get {
//            return this.inputVariablesField;
//        }
//        set {
//            this.inputVariablesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("variable", typeof(variable), IsNullable=false)]
//    public variable[][] outputVariables {
//        get {
//            return this.outputVariablesField;
//        }
//        set {
//            this.outputVariablesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("data", typeof(addDataData), IsNullable=false)]
//    public addDataData[][] addData {
//        get {
//            return this.addDataField;
//        }
//        set {
//            this.addDataField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string typeName {
//        get {
//            return this.typeNameField;
//        }
//        set {
//            this.typeNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string instanceName {
//        get {
//            return this.instanceNameField;
//        }
//        set {
//            this.instanceNameField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDCoil {
    
//    private string connectionPointOutField;
    
//    private string variableField;
    
//    private position[] positionField;
    
//    private connectionPointInConnection[][] connectionPointInField;
    
//    private string localIdField;
    
//    private string negatedField;
    
//    private string storageField;
    
//    /// <remarks/>
//    public string connectionPointOut {
//        get {
//            return this.connectionPointOutField;
//        }
//        set {
//            this.connectionPointOutField = value;
//        }
//    }
    
//    /// <remarks/>
//    public string variable {
//        get {
//            return this.variableField;
//        }
//        set {
//            this.variableField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlArrayItemAttribute("connection", typeof(connectionPointInConnection), IsNullable=false)]
//    public connectionPointInConnection[][] connectionPointIn {
//        get {
//            return this.connectionPointInField;
//        }
//        set {
//            this.connectionPointInField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string negated {
//        get {
//            return this.negatedField;
//        }
//        set {
//            this.negatedField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string storage {
//        get {
//            return this.storageField;
//        }
//        set {
//            this.storageField = value;
//        }
//    }
//}

///// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.plcopen.org/xml/tc6_0200")]
//public partial class projectTypesPousPouBodyLDRightPowerRail {
    
//    private string connectionPointInField;
    
//    private position[] positionField;
    
//    private string localIdField;
    
//    /// <remarks/>
//    public string connectionPointIn {
//        get {
//            return this.connectionPointInField;
//        }
//        set {
//            this.connectionPointInField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("position")]
//    public position[] position {
//        get {
//            return this.positionField;
//        }
//        set {
//            this.positionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlAttributeAttribute()]
//    public string localId {
//        get {
//            return this.localIdField;
//        }
//        set {
//            this.localIdField = value;
//        }
//    }
//}
