//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from sample.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class sampleLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WS=1, EOL=2, COMMENT=3, TEXT=4;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"WS", "EOL", "COMMENT", "TEXT"
	};


	public sampleLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public sampleLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "WS", "EOL", "COMMENT", "TEXT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "sample.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static sampleLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,4,33,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,1,0,4,0,11,8,0,11,0,12,0,
		12,1,1,3,1,16,8,1,1,1,1,1,3,1,20,8,1,1,2,1,2,5,2,24,8,2,10,2,12,2,27,9,
		2,1,3,4,3,30,8,3,11,3,12,3,31,0,0,4,1,1,3,2,5,3,7,4,1,0,3,1,0,9,9,2,0,
		10,10,13,13,4,0,9,10,13,13,32,32,59,59,37,0,1,1,0,0,0,0,3,1,0,0,0,0,5,
		1,0,0,0,0,7,1,0,0,0,1,10,1,0,0,0,3,19,1,0,0,0,5,21,1,0,0,0,7,29,1,0,0,
		0,9,11,7,0,0,0,10,9,1,0,0,0,11,12,1,0,0,0,12,10,1,0,0,0,12,13,1,0,0,0,
		13,2,1,0,0,0,14,16,5,13,0,0,15,14,1,0,0,0,15,16,1,0,0,0,16,17,1,0,0,0,
		17,20,5,10,0,0,18,20,5,13,0,0,19,15,1,0,0,0,19,18,1,0,0,0,20,4,1,0,0,0,
		21,25,5,59,0,0,22,24,8,1,0,0,23,22,1,0,0,0,24,27,1,0,0,0,25,23,1,0,0,0,
		25,26,1,0,0,0,26,6,1,0,0,0,27,25,1,0,0,0,28,30,8,2,0,0,29,28,1,0,0,0,30,
		31,1,0,0,0,31,29,1,0,0,0,31,32,1,0,0,0,32,8,1,0,0,0,6,0,12,15,19,25,31,
		0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
